### ISSUE TITLE
基座应用如何控制子应用路由

### ISSUE THREAD

**Issue by 413281823** [micro-zoe/micro-app#11]
基座应用如何控制子应用路由

**Comment by bailicangdu** [comment]
基座和子应用是同一个url，就是页面的url，改变页面地址就可以影响到子应用，如果需要更加细粒度的控制，可以通过数据通信

**Comment by 413281823** [comment]
谢谢 我也发现了&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 基座应用如何控制子应用路由 (#11)





 
基座和子应用是同一个url，就是页面的url，改变页面地址就可以影响到子应用，如果需要更加细粒度的控制，可以通过数据通信

**Comment by linwaiwai** [comment]
如何手动控制子路由。

**Comment by sophiehu36** [comment]
有没有可能不改变基座的url控制子应用显示哪个页面呢？
