### ISSUE TITLE
有没有可能增加对子应用的viewport设置

### ISSUE THREAD

**Issue by coolRoger** [micro-zoe/micro-app#251]
我们现在在做一款基于react-mosaic的多窗口应用，每一个窗口都是一款子应用。

![image](https://user-images.githubusercontent.com/33861624/150243660-fb833d9f-d951-4ec1-83ea-4c44ee3b2e63.png)

每一款子应用都用了自适应布局，可是当应用窗口改变大小的时候，子应用的自适应布局没有生效，原因是子应用的viewport还是根据主应用的viewport来的，所以在想是否可以通过获取窗口的宽度传给子应用然后设置子应用的viewport，来使子应用元素可以自适应

**Comment by shiwanmenghuxiahuashan** [comment]
> 我们现在在做一款基于react-mosaic的多窗口应用，每一个窗口都是一款子应用。
> 
> ![image](https://user-images.githubusercontent.com/33861624/150243660-fb833d9f-d951-4ec1-83ea-4c44ee3b2e63.png)
> 
> 每一款子应用都用了自适应布局，可是当应用窗口改变大小的时候，子应用的自适应布局没有生效，原因是子应用的viewport还是根据主应用的viewport来的，所以在想是否可以通过获取窗口的宽度传给子应用然后设置子应用的viewport，来使子应用元素可以自适应

考虑通过基座应用传递 调整后 vw 或 vh 值给对应子应用，或直接设置对应的css变量使用呢？临时解决方案，可以先凑合用着

**Comment by coolRoger** [comment]
哈哈哈，现在回看，用CSS container queries能完美解决了
