### ISSUE TITLE
这个项目是不是不维护了？

### ISSUE THREAD

**Issue by shuyuTech** [micro-zoe/micro-app#703]
这个项目是不是不维护了？

**Comment by lanmingle** [comment]
哈哈哈！老老实实qiankun吧！感觉目前国内这些框架都不怎么靠谱，比如wujie就一个人维护什么的。

**Comment by raoenhui** [comment]
一直在维护中

**Comment by zhu-hongwei** [comment]
> 哈哈哈！老老实实qiankun吧！感觉目前国内这些框架都不怎么靠谱，比如wujie就一个人维护什么的。

## qiankun 在此 [https://github.com/umijs/qiankun/discussions/1378](https://github.com/umijs/qiankun/discussions/1378)
## 两年只更新了 logo ?

**Comment by Lizhooh** [comment]
> > 哈哈哈！老老实实qiankun吧！感觉目前国内这些框架都不怎么靠谱，比如wujie就一个人维护什么的。
> 
> ## qiankun 在此 [umijs/qiankun#1378](https://github.com/umijs/qiankun/discussions/1378)
> ## 两年只更新了 logo ?

一个人持续维护还不够，本身这种库代码量不多，你想 10 个人写 10 个思路？
