### ISSUE TITLE
1.x路由跳转到新的子应用只会到默认首页吗，如何主应用控制具体到哪个页面

### ISSUE THREAD

**Issue by lx18658730623** [micro-zoe/micro-app#765]
1.x路由跳转到新的子应用只会到默认首页吗，如何主应用控制具体到哪个页面

**Comment by codexu** [comment]
主应用通知子应用跳转一下就可以了

**Comment by bailicangdu** [comment]
如果没有关闭虚拟路由，可以通过设置default-page指定页面 https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

**Comment by lx18658730623** [comment]
> 如果没有关闭虚拟路由，可以通过设置default-page指定页面 https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

是可以解决的

**Comment by Vibing** [comment]
> 如果没有关闭虚拟路由，可以通过设置default-page指定页面 https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

如果关闭了虚拟路由，可以在父应用里直接跳转到指定页面的地址

**Comment by JieleeJie** [comment]
似乎只有在router-mode='search'才生效，router-mode='native'时没法跳转
