### ISSUE TITLE
子应用通过unpkg加载vue，无法渲染

### ISSUE THREAD

**Issue by lx18658730623** [micro-zoe/micro-app#766]
报错信息
![image](https://user-images.githubusercontent.com/51350848/231712413-bc554c8b-268f-410e-9271-923c79dc8f79.png)
主应用 vue3 +vite
子应用 vue3 +vite

子应用通过unpkg引入资源，本身可以正常访问
![image](https://user-images.githubusercontent.com/51350848/231712734-da6390c5-ef86-4a1d-8c21-99742cf69020.png)

但是放在主应用下就会报错

**Comment by bailicangdu** [comment]
需要将var Vue = xxx 改成window.Vue = xxx，但你这是第三方包，建议下载到本地引用，方便修改
